---

- name: Activate iocage
  block:

    - name: "Activate: Activate iocage pool {{ freebsd_iocage_pool }}"
      environment:
        CRYPTOGRAPHY_OPENSSL_NO_LEGACY: '1'
      register: result
      ansible.builtin.command:
        cmd: "iocage activate {{ freebsd_iocage_pool }}"
        creates: "{{ freebsd_iocage_mount }}"

    - name: "Activate: Debug result freebsd_iocage_debug={{ freebsd_iocage_debug }}"
      when: freebsd_iocage_debug | bool
      ansible.builtin.debug:
        var: result

  rescue:

    - name: "Activate: Debug rescue freebsd_iocage_debug={{ freebsd_iocage_debug }}"
      when: freebsd_iocage_debug | bool
      ansible.builtin.debug:
        msg: |
          {{ ansible_failed_task }}
          {{ ansible_failed_result }}

    - name: "Activate: End host."
      when: freebsd_iocage_activate_fatal | bool
      ansible.builtin.meta: end_host

# EOF
